#!/usr/bin/env python3
"""Fetch WallStreetCN news and render a simple HTML page to docs/index.html"""
from datetime import datetime
import os
import sys

# Ensure project root is on sys.path so imports work when script is executed from scripts/
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from get_wallstreat_news import get_wallstreetcn_news


def render_html(items):
    now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    rows = []
    for it in items:
        title = it.get('title', '')
        link = it.get('link', '#')
        dt = it.get('datetime', '')
        rows.append(f"<li><a href='{link}' target='_blank' rel='noopener noreferrer'>{title}</a> <small>{dt}</small></li>")

    rows_html = "\n      ".join(rows)

    body = f"""
<html>
  <head>
    <meta charset='utf-8'/>
    <title>WallStreetCN - Latest</title>
    <style>body{{font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial; padding:20px}} ul{{list-style:none;padding:0}} li{{margin:8px 0}} small{{color:#666;margin-left:8px}}</style>
  </head>
  <body>
    <h1>WallStreetCN - Latest (generated {now})</h1>
    <ul>
      {rows_html}
    </ul>
    <footer><p>Generated by GitHub Action</p></footer>
  </body>
</html>
"""
    return body


def main():
    items = get_wallstreetcn_news(use_cache=False)
    html = render_html(items)
    os.makedirs('docs', exist_ok=True)
    path = os.path.join('docs', 'index.html')
    with open(path, 'w', encoding='utf-8') as f:
        f.write(html)
    print('Wrote', path)


if __name__ == '__main__':
    main()
